services:
  station:
    build: ./station_app
    depends_on:
      - python_service
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_PYTHON_SERVICE_URL=http://python_service:8000

  python_service:
    build: ./python_backend
    ports:
      - "8000:8000"
